
/*
 * MarkupForm.java
 *
 * Created on Feb 5, 2013, 2:45:27 PM
 */
package org.openxdata.markup.ui;

import javax.swing.JButton;
import javax.swing.JMenuItem;
import javax.swing.text.JTextComponent;
import jsyntaxpane.DefaultSyntaxKit;
import jsyntaxpane.actions.CaretMonitor;

/**
 *
 * @author kay
 */
public class MarkupForm extends javax.swing.JFrame {

	/** Creates new form MarkupForm */
	public MarkupForm() {
		initComponents();

		DefaultSyntaxKit.registerContentType("text/xform", "org.openxdata.markup.ui.XFormMarkupSyntaxKit");
		txtMarkup.setContentType("text/xform");
		/*EditorKit kit = txtMarkup.getEditorKit();
		if (kit instanceof DefaultSyntaxKit) {
			DefaultSyntaxKit defaultSyntaxKit = (DefaultSyntaxKit) kit;
			defaultSyntaxKit.addToolBarActions(txtMarkup, jToolBar1);
		}*/
		new CaretMonitor(txtMarkup, lblCaret);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jToolBar1 = new javax.swing.JToolBar();
                btnGenerateXML = new javax.swing.JButton();
                btnShowXml = new javax.swing.JButton();
                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                lblCaret = new javax.swing.JLabel();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtMarkup = new javax.swing.JEditorPane();
                menuBar = new javax.swing.JMenuBar();
                fileMenu = new javax.swing.JMenu();
                menuOpen = new javax.swing.JMenuItem();
                menuSave = new javax.swing.JMenuItem();
                menuNew = new javax.swing.JMenuItem();
                exitMenuItem = new javax.swing.JMenuItem();
                jMenu1 = new javax.swing.JMenu();
                menuSimpleSkip = new javax.swing.JMenuItem();
                menuAdvancedSkip = new javax.swing.JMenuItem();
                menuOxdForm = new javax.swing.JMenuItem();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("Form MarkUp Builder");

                jToolBar1.setRollover(true);

                btnGenerateXML.setIcon(new javax.swing.ImageIcon(getClass().getResource("/play.png"))); // NOI18N
                btnGenerateXML.setToolTipText("Generate XML");
                btnGenerateXML.setFocusable(false);
                btnGenerateXML.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnGenerateXML.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                btnGenerateXML.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnGenerateXMLActionPerformed(evt);
                        }
                });
                jToolBar1.add(btnGenerateXML);

                btnShowXml.setFont(new java.awt.Font("Tahoma", 3, 11));
                btnShowXml.setText("SHOW XML");
                btnShowXml.setFocusable(false);
                btnShowXml.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                btnShowXml.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
                jToolBar1.add(btnShowXml);

                jLabel1.setText("Form Markup Line:");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 103, Short.MAX_VALUE)
                                .addComponent(lblCaret, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
                                .addComponent(lblCaret, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                jScrollPane1.setViewportView(txtMarkup);

                fileMenu.setMnemonic('f');
                fileMenu.setText("File");

                menuOpen.setText("Open");
                fileMenu.add(menuOpen);

                menuSave.setText("Save");
                fileMenu.add(menuSave);

                menuNew.setText("New");
                fileMenu.add(menuNew);

                exitMenuItem.setMnemonic('x');
                exitMenuItem.setText("Exit");
                exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                exitMenuItemActionPerformed(evt);
                        }
                });
                fileMenu.add(exitMenuItem);

                menuBar.add(fileMenu);

                jMenu1.setText("Examples");

                menuSimpleSkip.setText("Simple Skip Logic and Validation");
                jMenu1.add(menuSimpleSkip);

                menuAdvancedSkip.setText("Advanced Skip and Validation");
                jMenu1.add(menuAdvancedSkip);

                menuOxdForm.setText("OXD Sample Form");
                jMenu1.add(menuOxdForm);

                menuBar.add(jMenu1);

                setJMenuBar(menuBar);

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(112, 112, 112))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 371, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                );

                pack();
        }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
	    System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

private void btnGenerateXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateXMLActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_btnGenerateXMLActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(MarkupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(MarkupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(MarkupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(MarkupForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {

			public void run() {
				MarkupForm markupForm = new MarkupForm();
				markupForm.setLocationByPlatform(true);
				markupForm.setVisible(true);

			}
		});
	}

	public JTextComponent getTxtMarkUp() {
		return txtMarkup;
	}

	public JButton getBtnGenerateXML() {
		return btnGenerateXML;
	}

	public JMenuItem getMenuOpen() {
		return menuOpen;
	}

	public JMenuItem getMenuSave() {
		return menuSave;
	}

	public JMenuItem getMenuNew() {
		return menuNew;
	}

	public JButton getBtnShowXml() {
		return btnShowXml;
	}

	public JMenuItem getMenuSimpleSkip() {
		return menuSimpleSkip;
	}

	public JMenuItem getMenuOxdForm() {
		return menuOxdForm;
	}

	public JMenuItem getMenuAdvancedSkip() {
		return menuAdvancedSkip;
	}
	
	
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnGenerateXML;
        private javax.swing.JButton btnShowXml;
        private javax.swing.JMenuItem exitMenuItem;
        private javax.swing.JMenu fileMenu;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JMenu jMenu1;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JToolBar jToolBar1;
        private javax.swing.JLabel lblCaret;
        private javax.swing.JMenuItem menuAdvancedSkip;
        private javax.swing.JMenuBar menuBar;
        private javax.swing.JMenuItem menuNew;
        private javax.swing.JMenuItem menuOpen;
        private javax.swing.JMenuItem menuOxdForm;
        private javax.swing.JMenuItem menuSave;
        private javax.swing.JMenuItem menuSimpleSkip;
        private javax.swing.JEditorPane txtMarkup;
        // End of variables declaration//GEN-END:variables
}
