
/*
 * XFormView.java
 *
 * Created on Mar 1, 2013, 8:35:41 AM
 */
package org.openxdata.markup.ui;

import java.awt.*;
import java.io.IOException;
import java.io.StringReader;
import javax.swing.*;

import jsyntaxpane.DefaultSyntaxKit;

/**
 *
 * @author kay
 */
public class XFormView extends javax.swing.JPanel {

	/** Creates new form XFormView */
	public XFormView() {
    	initComponents();
        //text/xml=jsyntaxpane.syntaxkits.XmlSyntaxKit
        DefaultSyntaxKit.registerContentType("text/xml", "jsyntaxpane.syntaxkits.XmlSyntaxKit");

	}

	public void addLockedEditor(String name,String xml) {
		JScrollPane scrollPane = new javax.swing.JScrollPane();
		JEditorPane editorPane = new javax.swing.JEditorPane();
  		scrollPane.setViewportView(editorPane);
        editorPane.setContentType("text/xml");

        try {
            editorPane.read(new StringReader(xml), "text/xml");
        } catch (IOException ex) {
            // this probably wont happen?
        }
		jTabbedPane1.addTab(name, scrollPane);
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	
	public static XFormView initFrame(Frame owner) {
		XFormView view = new XFormView();
		JFrame frame = new JFrame("Preview");
        frame.setLocation(owner.getLocation());
        frame.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
		frame.setContentPane(view);
		frame.setVisible(true);
		frame.pack();

		return view;
	}
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jTabbedPane1 = new javax.swing.JTabbedPane();

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
                this.setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                );
        }// </editor-fold>//GEN-END:initComponents
        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JTabbedPane jTabbedPane1;
        // End of variables declaration//GEN-END:variables
}
